# Generated by Django 5.0.7 on 2024-08-12 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_alter_blog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='feature_image',
            field=models.ImageField(upload_to='uploads/%Y/%m/%d'),
        ),
    ]
